# Config specifying which trajectories to download from the remote.

  env: [
    'AbandonedFactory2',
    'AmericanDiner', 
    'ArchVizTinyHouseDay',
    'CountryHouse',
    'OldBrickHouseDay',
    'RetroOffice'
    ]
    
  difficulty: ['easy']
  modality: ['image', 'depth'] 
  camera_name: ['lcam_front', 'lcam_right', 'lcam_back', 'lcam_left', 'lcam_top', 'lcam_bottom']
  unzip: True
  delete_zip: False
  num_workers: 16